# Generated by Django 5.1a1 on 2024-06-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('userID', models.CharField(max_length=20, unique=True, verbose_name='用户编号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.CharField(max_length=50, verbose_name='电子邮箱')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(null=True, verbose_name='最后登录时间')),
                ('isFirstPW', models.BooleanField(default=True, verbose_name='是否初始密码')),
                ('uuid', models.CharField(max_length=100, verbose_name='设备信息')),
                ('fromType', models.IntegerField(verbose_name='来自信息')),
                ('fromTypeTitle', models.CharField(max_length=200, verbose_name='来自信息详情')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='userinfo_groups', related_query_name='userinfo', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='userinfo_user_permissions', related_query_name='userinfo', to='auth.permission')),
            ],
            options={
                'verbose_name': '注册用户信息',
                'verbose_name_plural': '注册用户信息',
                'db_table': 'tb_user_info',
            },
        ),
    ]
