# Generated by Django 5.1a1 on 2024-06-26 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator], verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fromType',
            field=models.IntegerField(choices=[(1, 'web官网'), (2, '类型2'), (3, '类型3')], verbose_name='来自信息'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='用户所属的组。', related_name='userinfo_groups', related_query_name='userinfo', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='用户的特定权限。', related_name='userinfo_user_permissions', related_query_name='userinfo', to='auth.permission'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['username'], name='tb_user_inf_usernam_60f430_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['userID'], name='tb_user_inf_userID_04207e_idx'),
        ),
    ]
