# Generated by Django 5.1a1 on 2024-06-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subtitle_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100, verbose_name='用户ID')),
                ('imageURL', models.CharField(max_length=100, verbose_name='上传图片地址')),
                ('sub_mak_imageURL', models.CharField(max_length=100, verbose_name='带水印的拼接地址')),
                ('sub_imageURL', models.CharField(max_length=100, verbose_name='无水印的拼接地址')),
                ('subTitle', models.CharField(max_length=200, verbose_name='标题')),
                ('subDescription', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '字幕图片数据',
                'verbose_name_plural': '字幕图片数据',
                'db_table': 'subtitle_data',
            },
        ),
    ]
